# Generated by carnix 0.10.0: carnix generate-nix --standalone --src .
{ lib, buildRustCrate, buildRustCrateHelpers, callPackage, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# sticker-python-0.1.0

    crates.sticker_python."0.1.0" = deps: { features?(features_.sticker_python."0.1.0" deps {}) }: buildRustCrate {
      crateName = "sticker-python";
      version = "0.1.0";
      description = "Sticker Python module";
      authors = [ "Daniël de Kok <me@danieldk.eu>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      libName = "sticker";
      type = [ "cdylib" ];
      dependencies = mapFeatures features ([
        (cratesIO.crates."conllx"."${deps."sticker_python"."0.1.0"."conllx"}" deps)
        (cratesIO.crates."pyo3"."${deps."sticker_python"."0.1.0"."pyo3"}" deps)
        (cratesIO.crates."sticker_utils"."${deps."sticker_python"."0.1.0"."sticker_utils"}" deps)
      ]);
    };
    features_.sticker_python."0.1.0" = deps: f: updateFeatures f (rec {
      conllx."${deps.sticker_python."0.1.0".conllx}".default = true;
      pyo3 = fold recursiveUpdate {} [
        { "${deps.sticker_python."0.1.0".pyo3}"."extension-module" = true; }
        { "${deps.sticker_python."0.1.0".pyo3}".default = true; }
      ];
      sticker_python."0.1.0".default = (f.sticker_python."0.1.0".default or true);
      sticker_utils."${deps.sticker_python."0.1.0".sticker_utils}".default = true;
    }) [
      (cratesIO.features_.conllx."${deps."sticker_python"."0.1.0"."conllx"}" deps)
      (cratesIO.features_.pyo3."${deps."sticker_python"."0.1.0"."pyo3"}" deps)
      (cratesIO.features_.sticker_utils."${deps."sticker_python"."0.1.0"."sticker_utils"}" deps)
    ];


# end

  };

  sticker_python = crates.crates.sticker_python."0.1.0" deps;
  __all = [ (sticker_python {}) ];
  deps.adler32."1.0.3" = {};
  deps.aho_corasick."0.7.6" = {
    memchr = "2.2.1";
  };
  deps.aligned_alloc."0.1.3" = {
    kernel32_sys = "0.2.2";
    libc = "0.2.62";
    winapi = "0.2.8";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.7";
  };
  deps.arrayvec."0.4.11" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.13" = {
    libc = "0.2.62";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.5" = {};
  deps.backtrace."0.3.32" = {
    backtrace_sys = "0.1.30";
    cfg_if = "0.1.9";
    libc = "0.2.62";
    rustc_demangle = "0.1.15";
  };
  deps.backtrace_sys."0.1.30" = {
    libc = "0.2.62";
    cc = "1.0.37";
  };
  deps.bitflags."1.1.0" = {};
  deps.build_const."0.2.1" = {};
  deps.byteorder."1.3.2" = {};
  deps.c2_chacha."0.2.2" = {
    lazy_static = "1.3.0";
    ppv_lite86 = "0.2.5";
  };
  deps.cc."1.0.37" = {};
  deps.cfg_if."0.1.9" = {};
  deps.clap."2.33.0" = {
    atty = "0.2.13";
    bitflags = "1.1.0";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.clicolors_control."1.0.0" = {
    lazy_static = "1.3.0";
    libc = "0.2.62";
    atty = "0.2.13";
    winapi = "0.3.7";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.1.0";
  };
  deps.conllx."0.12.1" = {
    failure = "0.1.5";
    itertools = "0.8.0";
    petgraph = "0.4.13";
  };
  deps.console."0.7.7" = {
    atty = "0.2.13";
    clicolors_control = "1.0.0";
    lazy_static = "1.3.0";
    libc = "0.2.62";
    parking_lot = "0.9.0";
    regex = "1.3.1";
    unicode_width = "0.1.5";
    termios = "0.3.1";
    encode_unicode = "0.3.5";
    winapi = "0.3.7";
  };
  deps.crc."1.8.1" = {
    build_const = "0.2.1";
  };
  deps.crc32fast."1.2.0" = {
    cfg_if = "0.1.9";
  };
  deps.crossbeam_deque."0.6.3" = {
    crossbeam_epoch = "0.7.1";
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_epoch."0.7.1" = {
    arrayvec = "0.4.11";
    cfg_if = "0.1.9";
    crossbeam_utils = "0.6.5";
    lazy_static = "1.3.0";
    memoffset = "0.2.1";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_queue."0.1.2" = {
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_utils."0.6.5" = {
    cfg_if = "0.1.9";
    lazy_static = "1.3.0";
  };
  deps.ctor."0.1.9" = {
    quote = "0.6.13";
    syn = "0.15.39";
  };
  deps.curl."0.4.22" = {
    curl_sys = "0.4.20";
    libc = "0.2.62";
    socket2 = "0.3.9";
    openssl_probe = "0.1.2";
    openssl_sys = "0.9.47";
    kernel32_sys = "0.2.2";
    schannel = "0.1.15";
    winapi = "0.2.8";
  };
  deps.curl_sys."0.4.20" = {
    libc = "0.2.62";
    libz_sys = "1.0.25";
    cc = "1.0.37";
    pkg_config = "0.3.14";
    openssl_sys = "0.9.47";
    winapi = "0.3.7";
  };
  deps.either."1.5.2" = {};
  deps.encode_unicode."0.3.5" = {};
  deps.failure."0.1.5" = {
    backtrace = "0.3.32";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.39";
    synstructure = "0.10.2";
  };
  deps.filetime."0.2.6" = {
    cfg_if = "0.1.9";
    redox_syscall = "0.1.56";
    libc = "0.2.62";
    winapi = "0.3.7";
  };
  deps.finalfusion."0.10.1" = {
    byteorder = "1.3.2";
    fnv = "1.0.6";
    itertools = "0.8.0";
    memmap = "0.7.0";
    ndarray = "0.12.1";
    ordered_float = "1.0.2";
    rand = "0.7.2";
    rand_xorshift = "0.2.0";
    reductive = "0.3.0";
    serde = "1.0.101";
    toml = "0.5.1";
  };
  deps.fixedbitset."0.1.9" = {};
  deps.flate2."1.0.9" = {
    crc32fast = "1.2.0";
    libc = "0.2.62";
    miniz_sys = "0.1.12";
    miniz_oxide_c_api = "0.2.2";
  };
  deps.fnv."1.0.6" = {};
  deps.getrandom."0.1.12" = {
    cfg_if = "0.1.9";
    libc = "0.2.62";
    wasi = "0.7.0";
  };
  deps.ghost."0.1.0" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.39";
  };
  deps.half."1.3.0" = {};
  deps.indicatif."0.11.0" = {
    console = "0.7.7";
    lazy_static = "1.3.0";
    number_prefix = "0.2.8";
    parking_lot = "0.9.0";
    regex = "1.3.1";
  };
  deps.indoc."0.3.4" = {
    indoc_impl = "0.3.4";
    proc_macro_hack = "0.5.9";
  };
  deps.indoc_impl."0.3.4" = {
    proc_macro_hack = "0.5.9";
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
    unindent = "0.1.4";
  };
  deps.inventory."0.1.4" = {
    ctor = "0.1.9";
    ghost = "0.1.0";
    inventory_impl = "0.1.4";
  };
  deps.inventory_impl."0.1.4" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.itertools."0.7.11" = {
    either = "1.5.2";
  };
  deps.itertools."0.8.0" = {
    either = "1.5.2";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.62" = {};
  deps.libz_sys."1.0.25" = {
    libc = "0.2.62";
    cc = "1.0.37";
    pkg_config = "0.3.14";
  };
  deps.lock_api."0.3.1" = {
    scopeguard = "1.0.0";
  };
  deps.log."0.4.7" = {
    cfg_if = "0.1.9";
  };
  deps.matrixmultiply."0.1.15" = {
    rawpointer = "0.1.0";
  };
  deps.memchr."2.2.1" = {};
  deps.memmap."0.7.0" = {
    libc = "0.2.62";
    winapi = "0.3.7";
  };
  deps.memoffset."0.2.1" = {};
  deps.miniz_sys."0.1.12" = {
    libc = "0.2.62";
    cc = "1.0.37";
  };
  deps.miniz_oxide."0.2.2" = {
    adler32 = "1.0.3";
  };
  deps.miniz_oxide_c_api."0.2.2" = {
    crc32fast = "1.2.0";
    libc = "0.2.62";
    miniz_oxide = "0.2.2";
    cc = "1.0.37";
  };
  deps.ndarray."0.12.1" = {
    itertools = "0.7.11";
    matrixmultiply = "0.1.15";
    num_complex = "0.2.3";
    num_traits = "0.2.8";
  };
  deps.ndarray_parallel."0.9.0" = {
    ndarray = "0.12.1";
    rayon = "1.1.0";
  };
  deps.ndarray_tensorflow."0.2.0" = {
    ndarray = "0.12.1";
    tensorflow = "0.13.0";
  };
  deps.nodrop."0.1.13" = {};
  deps.num_complex."0.2.3" = {
    num_traits = "0.2.8";
    autocfg = "0.1.5";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.5";
  };
  deps.num_cpus."1.10.1" = {
    libc = "0.2.62";
  };
  deps.number_prefix."0.2.8" = {
    num_traits = "0.2.8";
  };
  deps.openssl_probe."0.1.2" = {};
  deps.openssl_sys."0.9.47" = {
    libc = "0.2.62";
    autocfg = "0.1.5";
    cc = "1.0.37";
    pkg_config = "0.3.14";
  };
  deps.ordered_float."1.0.2" = {
    num_traits = "0.2.8";
    serde = "1.0.101";
  };
  deps.ordermap."0.3.5" = {};
  deps.parking_lot."0.9.0" = {
    lock_api = "0.3.1";
    parking_lot_core = "0.6.1";
    rustc_version = "0.2.3";
  };
  deps.parking_lot_core."0.6.1" = {
    cfg_if = "0.1.9";
    smallvec = "0.6.10";
    rustc_version = "0.2.3";
    cloudabi = "0.0.3";
    redox_syscall = "0.1.56";
    libc = "0.2.62";
    winapi = "0.3.7";
  };
  deps.paste."0.1.6" = {
    paste_impl = "0.1.6";
    proc_macro_hack = "0.5.9";
  };
  deps.paste_impl."0.1.6" = {
    proc_macro_hack = "0.5.9";
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.petgraph."0.4.13" = {
    fixedbitset = "0.1.9";
    ordermap = "0.3.5";
  };
  deps.pkg_config."0.3.14" = {};
  deps.ppv_lite86."0.2.5" = {};
  deps.proc_macro_hack."0.5.9" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.proc_macro2."1.0.3" = {
    unicode_xid = "0.2.0";
  };
  deps.protobuf."2.8.0" = {};
  deps.pyo3."0.8.0" = {
    indoc = "0.3.4";
    inventory = "0.1.4";
    libc = "0.2.62";
    num_traits = "0.2.8";
    paste = "0.1.6";
    pyo3cls = "0.8.0";
    spin = "0.5.2";
    unindent = "0.1.4";
    regex = "1.3.1";
    serde = "1.0.101";
    serde_json = "1.0.40";
    version_check = "0.9.1";
  };
  deps.pyo3_derive_backend."0.8.0" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.pyo3cls."0.8.0" = {
    proc_macro2 = "1.0.3";
    pyo3_derive_backend = "0.8.0";
    quote = "1.0.2";
    syn = "1.0.5";
  };
  deps.quote."0.6.13" = {
    proc_macro2 = "0.4.30";
  };
  deps.quote."1.0.2" = {
    proc_macro2 = "1.0.3";
  };
  deps.rand."0.7.2" = {
    rand_core = "0.5.1";
    rand_pcg = "0.2.0";
    rand_chacha = "0.2.1";
    rand_hc = "0.2.0";
    libc = "0.2.62";
  };
  deps.rand_chacha."0.2.1" = {
    c2_chacha = "0.2.2";
    rand_core = "0.5.1";
  };
  deps.rand_core."0.5.1" = {
    getrandom = "0.1.12";
  };
  deps.rand_hc."0.2.0" = {
    rand_core = "0.5.1";
  };
  deps.rand_pcg."0.2.0" = {
    rand_core = "0.5.1";
    autocfg = "0.1.5";
  };
  deps.rand_xorshift."0.2.0" = {
    rand_core = "0.5.1";
  };
  deps.rawpointer."0.1.0" = {};
  deps.rayon."1.1.0" = {
    crossbeam_deque = "0.6.3";
    either = "1.5.2";
    rayon_core = "1.5.0";
  };
  deps.rayon_core."1.5.0" = {
    crossbeam_deque = "0.6.3";
    crossbeam_queue = "0.1.2";
    crossbeam_utils = "0.6.5";
    lazy_static = "1.3.0";
    num_cpus = "1.10.1";
  };
  deps.redox_syscall."0.1.56" = {};
  deps.reductive."0.3.0" = {
    log = "0.4.7";
    ndarray = "0.12.1";
    ndarray_parallel = "0.9.0";
    num_traits = "0.2.8";
    ordered_float = "1.0.2";
    rand = "0.7.2";
    rand_core = "0.5.1";
    rand_xorshift = "0.2.0";
    rayon = "1.1.0";
  };
  deps.regex."1.3.1" = {
    aho_corasick = "0.7.6";
    memchr = "2.2.1";
    regex_syntax = "0.6.12";
    thread_local = "0.3.6";
  };
  deps.regex_syntax."0.6.12" = {};
  deps.rustc_demangle."0.1.15" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."1.0.0" = {};
  deps.schannel."0.1.15" = {
    lazy_static = "1.3.0";
    winapi = "0.3.7";
  };
  deps.scopeguard."0.3.3" = {};
  deps.scopeguard."1.0.0" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.101" = {
    serde_derive = "1.0.95";
  };
  deps.serde_cbor."0.10.1" = {
    byteorder = "1.3.2";
    half = "1.3.0";
    serde = "1.0.101";
  };
  deps.serde_derive."1.0.95" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.39";
  };
  deps.serde_json."1.0.40" = {
    itoa = "0.4.4";
    ryu = "1.0.0";
    serde = "1.0.101";
  };
  deps.smallvec."0.6.10" = {};
  deps.socket2."0.3.9" = {
    cfg_if = "0.1.9";
    libc = "0.2.62";
    redox_syscall = "0.1.56";
    winapi = "0.3.7";
  };
  deps.spin."0.5.2" = {};
  deps.stdinout."0.4.0" = {};
  deps.sticker."0.9.0" = {
    conllx = "0.12.1";
    failure = "0.1.5";
    finalfusion = "0.10.1";
    itertools = "0.8.0";
    ndarray = "0.12.1";
    ndarray_tensorflow = "0.2.0";
    ordered_float = "1.0.2";
    petgraph = "0.4.13";
    protobuf = "2.8.0";
    serde = "1.0.101";
    serde_derive = "1.0.95";
    sticker_tf_proto = "0.7.0";
    tensorflow = "0.13.0";
  };
  deps.sticker_python."0.1.0" = {
    conllx = "0.12.1";
    pyo3 = "0.8.0";
    sticker_utils = "0.9.0";
  };
  deps.sticker_tf_proto."0.7.0" = {
    protobuf = "2.8.0";
  };
  deps.sticker_utils."0.9.0" = {
    clap = "2.33.0";
    conllx = "0.12.1";
    failure = "0.1.5";
    finalfusion = "0.10.1";
    indicatif = "0.11.0";
    ordered_float = "1.0.2";
    serde = "1.0.101";
    serde_cbor = "0.10.1";
    serde_derive = "1.0.95";
    stdinout = "0.4.0";
    sticker = "0.9.0";
    tensorflow = "0.13.0";
    threadpool = "1.7.1";
    toml = "0.5.1";
  };
  deps.strsim."0.8.0" = {};
  deps.syn."0.15.39" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    unicode_xid = "0.1.0";
  };
  deps.syn."1.0.5" = {
    proc_macro2 = "1.0.3";
    quote = "1.0.2";
    unicode_xid = "0.2.0";
  };
  deps.synstructure."0.10.2" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.39";
    unicode_xid = "0.1.0";
  };
  deps.tar."0.4.26" = {
    filetime = "0.2.6";
    redox_syscall = "0.1.56";
    libc = "0.2.62";
    xattr = "0.2.2";
  };
  deps.tensorflow."0.13.0" = {
    aligned_alloc = "0.1.3";
    byteorder = "1.3.2";
    crc = "1.8.1";
    libc = "0.2.62";
    num_complex = "0.2.3";
    tensorflow_sys = "0.16.0";
  };
  deps.tensorflow_sys."0.16.0" = {
    libc = "0.2.62";
    curl = "0.4.22";
    flate2 = "1.0.9";
    pkg_config = "0.3.14";
    semver = "0.9.0";
    tar = "0.4.26";
  };
  deps.termios."0.3.1" = {
    libc = "0.2.62";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.threadpool."1.7.1" = {
    num_cpus = "1.10.1";
  };
  deps.toml."0.5.1" = {
    serde = "1.0.101";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.unicode_xid."0.2.0" = {};
  deps.unindent."0.1.4" = {};
  deps.vcpkg."0.2.7" = {};
  deps.vec_map."0.8.1" = {};
  deps.version_check."0.9.1" = {};
  deps.wasi."0.7.0" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.xattr."0.2.2" = {
    libc = "0.2.62";
  };
}
